NAME="AeroLite OS"
VERSION="0.1.0-dev"
CODENAME="Skyfall"

DE="LXQt"
WM="Openbox"

DISTRO="Arch Linux"
PACKAGE_MANAGER="pacman"

THEME="AeroLite"
ICONS="AeroLite"
CURSOR="Bibata-Modern-Ice"

SPLASH="AeroLite"
